### ISSUE TITLE
有 JB版的Compose 範例嗎 ?

### ISSUE THREAD

**Issue by CMingTseng** [luhenchang/ComposeUnit#1]
大神你好

最近在看 Compose 

但是Android版的 Compose需要 4.2以上的AS才可以執行

找了一下 

Compose for Desktop, by JetBrains

這個可以在一般版本的AS上跑

(在   KMP的基礎上   把 Android  的Compose 修改  )

(其中的org.jetbrains.compose:compose-gradle-plugin 是關鍵  他替換了部分)

其中

的Todo範例

https://github.com/JetBrains/compose-jb/tree/master/examples/todoapp

而 Compose 也讓其他人很好奇

所以有其他人做了web版的demo  !! 

https://github.com/ShikaSD/compose-server-side

同樣也是 Todo範例

但是Web版的  使用  特化編譯過的   org.jetbrains.kotlin.jvm     
與
一些plugin  

androidx.compose:compose-compiler:0.1.0-dev15

org.jetbrains.kotlinx:kotlinx-serialization-runtime:0.20.0-1.4-M3

org.jetbrains.kotlin:kotlin-compiler-embeddable:1.4.0-dev-withExperimentalGoogleExtensions-20200720

不知道大神可以幫忙研究看看

怎麼 替換成 Compose for Desktop

這樣就可以一套 Compose  應用在各平台上

謝謝

**Comment by luhenchang** [comment]
时间比较少。当然我也写了相关mac端的一些案例:https://juejin.cn/post/6949446764839567374
